# Generated by Django 3.0.7 on 2020-07-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
